title: Utsav Ajay # your name (or website title) here
logo: "/images/072222carlson020.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio! 
  Check out some of the projects I have worked on!  
  <a href="https://www.linkedin.com/in/utsav-ajay/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-4Y06HDDLKZ # your Google Analytics tracking ID here
