title: Utsav Ajay # your name (or website title) here
logo: "/images/072222carlson020-1.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Welcome! I have nearly 3 years of analytics experience in healthcare and fintech,
  where I have worked on various cool things, ranging from product launch strategy,
  experimentation, network analysis, and competitior intelligence. I love to get my hands dirty
  with data, while seeing the bigger business vision.
 
  <br><br>
  <a href="https://www.linkedin.com/in/utsav-ajay/">View My LinkedIn Profile</a> 
  <a href="https://drive.google.com/file/d/16H53qvU8iVm8CwVBqdIacxCzKp_dPECo/view?usp=share_link">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-4Y06HDDLKZ # your Google Analytics tracking ID here
